name: Client Build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Install NPM dependencies
        run: npm install
      - name: Run Prettier
        run: npm run prettier:check
      - name: Run Lint
        run: npm run lint
      - name: Run Test
        run: npm run test -- --coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
