name: Client Build

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "client/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: client

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20.x"
      - name: Install NPM dependencies
        run: npm install
      - name: Run Prettier
        run: npm run prettier
      - name: Run Lint
        run: npm run lint
      - name: Run Test
        run: npm run test:coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./client/coverage/lcov.info
          base-path: ./client
